### PR TITLE
Add possibility to update the status from cli 

### PR DESCRIPTION
**Pull request by allan-simon**
this mr add the possibility to update the status of  a given issue using 

```
redmine update 1234  closed
```

or 

```
redmine update 1234 "in progress"
```

[EDIT]: it now works 
1. at first I forgot to send the json header in the request
2. redmine API expact status_id value to be a string

### CODE REVIEW

**Comment by allan-simon** [comment]
for the travis build failed,  does master actually pass ? because I have tested my code on ubuntu 14.04 and it works correctly :/ (tomorrow I will check more in details the Travis log)

**Comment by yanjost** [comment]
Try to merge with the current HEAD, the build should pass

**Comment by allan-simon** [comment]
I updated,

the line split was to be  < 80 char, and I found it more readable, but it's your call :)

**Comment by allan-simon** [comment]
it seems it does not like the "dictionnary comprehension" syntax on 2.6, if you want support for 2.6 tell me and I will adapt the code.  (stating on the README page what version of python you support may help future contributor)

**Comment by yanjost** [comment]
Yes currently we are supporting 2.6, but I'm thinking about dropping it

**Comment by allan-simon** [comment]
I've replaced by the syntax compatible for 2.6 should be good to merge now :)

**Comment by allan-simon** [comment]
any updates ?

**Comment by yanjost** [comment]
Thank you allan for your contribution and sorry for the delay !

**Pull request merged**
